version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      maven:
        patterns:
          - "*"
    ignore:
      - dependency-name: "androidx.core:core-ktx"