name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches: 
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: 'recursive'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@main

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Accept Licenses
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: app
          path: app/build/outputs/apk/*
